### ISSUE TITLE
Unable to Run the report on NUIX 8

### ISSUE THREAD

**Issue by Venny2020** [Nuix/Tiered-Report#5]
I downloaded the ZIP file and extracted it to NUIX script directory. I opened a case and tried running the script from Ruby module. I am getting below error.

(LoadError) no such file to load -- C:/Users/venny/AppData/Roaming/Nuix/Scripts/Tiered-Report-master (1)/Tiered-Report-master/Ruby/TieredReport.nuixscript/Nx

Should I copy anything else into the script directory along with the Tiered script?

**Comment by JuicyDragon** [comment]
Hello @Venny2020 I believe you downloaded using the big green download button rather than from the [releases section](https://github.com/Nuix/Tiered-Report/releases).  The green download button downloads a copy of the repository, which is basically just the source code, so that won't contain the compiled JAR files (such as Nx.jar) that the script relies on.  If you download a Zip from the [releases section](https://github.com/Nuix/Tiered-Report/releases) that should contain all the bits you need to run the script.

**Comment by Venny2020** [comment]
Hi Jason,

You are right, I did the download from the green download button. Good to
know, where to download from ;)

It is working now Jason. Thanks again!

--
Regards,
Venny.

**Comment by JuicyDragon** [comment]
Excellent, glad to hear it.
